### ISSUE TITLE
Générateur de json d'évent

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/Tools#3]

**Comment by symsym-1629** [comment]
Donc liste rapide des modif / ajouts à faire

- [x] compléter la liste des effets
- [x] dropdown pour les effets
- [x] checkboxes pour les booléens
- [ ] Modification d'un event déjà dans le jeu

**Comment by leuhvraiminoryo** [comment]
pour la modif d'évent déjà dans le jeu, faut d'abord rajouter la prise en compte d'autres conditions de trigger + les "effets di'ssue" comme mapLink et nextEvent

**Comment by leuhvraiminoryo** [comment]
:warning: *très léger* (non, plutôt majeur) bug sur le gen, qui renseigne dans le json les valeurs entrées de health et timeloss sous forme de strings

+ dans les jsons d'évents, contrairement à dans le fichier report.json, faut mettre lostTime et pas timeLost

faut donc fixer ça ~

**Comment by Nargacaura** [comment]
Pas que ça, visiblement, y'a aussi un manque de cohérence dans les effets secondaires:
https://github.com/DraftBot-A-Discord-Adventure/Tools/blob/36a41813481132e57703b9b671201c77c2308f5d/generators/events.html#L158
Comme ça peut se remarquer, `dizzy_face` manque le premier ':', et `confounded` et `lock` les manquent entièrement. Il se peut donc qu'il casse aussi à ce niveau-là.

**Comment by leuhvraiminoryo** [comment]
> Pas que ça, visiblement, y'a aussi un manque de cohérence dans les effets secondaires:
> 
> https://github.com/DraftBot-A-Discord-Adventure/Tools/blob/36a41813481132e57703b9b671201c77c2308f5d/generators/events.html#L158
> 
> Comme ça peut se remarquer, `dizzy_face` manque le premier ':', et `confounded` et `lock` les manquent entièrement. Il se peut donc qu'il casse aussi à ce niveau-là.

alors ye mais j'avais pas use le truc pour les effets car on savait déjà que c'était incomplet (still à arranger ofc)

**Comment by leuhvraiminoryo** [comment]
faut rajouter que pour les items faut "randomItem" et pas "item" juste

**Comment by leuhvraiminoryo** [comment]
btw du coup j'vais modifier ça demain, au moins jusqu'à avoir un truc pas immensément buggé

**Comment by leuhvraiminoryo** [comment]
Les bugs rapportés hier ont normalement été fixés (je vérifierai ça plus en détails soon mais là j'veux manger puis j'ai des DS), et l'ajout des effets est amélioré.

Il reste à faire les checkboxes pour les choses booléennes, et ça devrait être okay

(la modification d'events déjà existants, comme dit plusieurs messages auparavant, ça demande pas mal d'autres trucs, je pense donc que ça mérite une issue à part)

**Comment by leuhvraiminoryo** [comment]
Eeeeeeet... j'ai encore oublié de mentionner l'issue dans mon commit ~

Mais bref, le gen est fait de façon assez correcte désormais.

Je ferme donc l'issue
